//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2CTouresBalon.ServicioOrdenes {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public partial class ConsultarClientesOrdenesFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error consultarClientesOrdenesFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarClientesOrdenesFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ConsultarClientesOrdenesFault1 {
            get {
                return this.consultarClientesOrdenesFault1Field;
            }
            set {
                this.consultarClientesOrdenesFault1Field = value;
                this.RaisePropertyChanged("ConsultarClientesOrdenesFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_itemField;
        
        private int id_prodField;
        
        private string nombre_prodField;
        
        private string part_numField;
        
        private double precioField;
        
        private int cantidadField;
        
        private int id_ordenField;
        
        private bool id_ordenFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id_item {
            get {
                return this.id_itemField;
            }
            set {
                this.id_itemField = value;
                this.RaisePropertyChanged("id_item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_prod {
            get {
                return this.id_prodField;
            }
            set {
                this.id_prodField = value;
                this.RaisePropertyChanged("id_prod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre_prod {
            get {
                return this.nombre_prodField;
            }
            set {
                this.nombre_prodField = value;
                this.RaisePropertyChanged("nombre_prod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string part_num {
            get {
                return this.part_numField;
            }
            set {
                this.part_numField = value;
                this.RaisePropertyChanged("part_num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int id_orden {
            get {
                return this.id_ordenField;
            }
            set {
                this.id_ordenField = value;
                this.RaisePropertyChanged("id_orden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_ordenSpecified {
            get {
                return this.id_ordenFieldSpecified;
            }
            set {
                this.id_ordenFieldSpecified = value;
                this.RaisePropertyChanged("id_ordenSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public partial class Orden : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_clienteField;
        
        private int id_ordenField;
        
        private bool id_ordenFieldSpecified;
        
        private System.DateTime fecha_ordenField;
        
        private double precioField;
        
        private EstatusOrden estatusField;
        
        private bool estatusFieldSpecified;
        
        private string[] comentariosField;
        
        private Item[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                this.id_clienteField = value;
                this.RaisePropertyChanged("id_cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_orden {
            get {
                return this.id_ordenField;
            }
            set {
                this.id_ordenField = value;
                this.RaisePropertyChanged("id_orden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_ordenSpecified {
            get {
                return this.id_ordenFieldSpecified;
            }
            set {
                this.id_ordenFieldSpecified = value;
                this.RaisePropertyChanged("id_ordenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fecha_orden {
            get {
                return this.fecha_ordenField;
            }
            set {
                this.fecha_ordenField = value;
                this.RaisePropertyChanged("fecha_orden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public EstatusOrden estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("estatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estatusSpecified {
            get {
                return this.estatusFieldSpecified;
            }
            set {
                this.estatusFieldSpecified = value;
                this.RaisePropertyChanged("estatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comentarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string[] comentarios {
            get {
                return this.comentariosField;
            }
            set {
                this.comentariosField = value;
                this.RaisePropertyChanged("comentarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public Item[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public enum EstatusOrden {
        
        /// <remarks/>
        VALIDACION,
        
        /// <remarks/>
        RESERVACION,
        
        /// <remarks/>
        CERRADA,
        
        /// <remarks/>
        RECHAZADA,
        
        /// <remarks/>
        CANCELADA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public partial class CancelarOrdenesFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error cancelarOrdenesFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CancelarOrdenesFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error CancelarOrdenesFault1 {
            get {
                return this.cancelarOrdenesFault1Field;
            }
            set {
                this.cancelarOrdenesFault1Field = value;
                this.RaisePropertyChanged("CancelarOrdenesFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public partial class CrearOrdenesFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error crearOrdenesFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CrearOrdenesFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error CrearOrdenesFault1 {
            get {
                return this.crearOrdenesFault1Field;
            }
            set {
                this.crearOrdenesFault1Field = value;
                this.RaisePropertyChanged("CrearOrdenesFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public partial class ConsultarOrdenesFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error consultarOrdenesFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarOrdenesFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ConsultarOrdenesFault1 {
            get {
                return this.consultarOrdenesFault1Field;
            }
            set {
                this.consultarOrdenesFault1Field = value;
                this.RaisePropertyChanged("ConsultarOrdenesFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public partial class ConsultarRangoCerradoOrdenesFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error consultarRangoCerradoOrdenesFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarRangoCerradoOrdenesFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ConsultarRangoCerradoOrdenesFault1 {
            get {
                return this.consultarRangoCerradoOrdenesFault1Field;
            }
            set {
                this.consultarRangoCerradoOrdenesFault1Field = value;
                this.RaisePropertyChanged("ConsultarRangoCerradoOrdenesFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public partial class ConsultarRankingAbiertasOrdenesFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error consultarRankingAbiertasOrdenesFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarRankingAbiertasOrdenesFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ConsultarRankingAbiertasOrdenesFault1 {
            get {
                return this.consultarRankingAbiertasOrdenesFault1Field;
            }
            set {
                this.consultarRankingAbiertasOrdenesFault1Field = value;
                this.RaisePropertyChanged("ConsultarRankingAbiertasOrdenesFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public partial class ConsultarRankingCerradoOrdenesFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error consultarRankingCerradoOrdenesFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarRankingCerradoOrdenesFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ConsultarRankingCerradoOrdenesFault1 {
            get {
                return this.consultarRankingCerradoOrdenesFault1Field;
            }
            set {
                this.consultarRankingCerradoOrdenesFault1Field = value;
                this.RaisePropertyChanged("ConsultarRankingCerradoOrdenesFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/", ConfigurationName="ServicioOrdenes.OrdenesTouresBalon")]
    public interface OrdenesTouresBalon {
        
        // CODEGEN: Parameter 'orden' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/OrdenesTouresBalon/ConsultarClientesOrdenes", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioOrdenes.ConsultarClientesOrdenesFault), Action="http://www.touresbalon.com/OrdenesTouresBalon/ConsultarClientesOrdenes", Name="ConsultarClientesOrdenesFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="orden")]
        B2CTouresBalon.ServicioOrdenes.ConsultarClientesOrdenesResponse ConsultarClientesOrdenes(B2CTouresBalon.ServicioOrdenes.ConsultarClientesOrdenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/OrdenesTouresBalon/ConsultarClientesOrdenes", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.ConsultarClientesOrdenesResponse> ConsultarClientesOrdenesAsync(B2CTouresBalon.ServicioOrdenes.ConsultarClientesOrdenesRequest request);
        
        // CODEGEN: Parameter 'respuesta' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/OrdenesTouresBalon/CancelarOrdenes", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioOrdenes.CancelarOrdenesFault), Action="http://www.touresbalon.com/OrdenesTouresBalon/CancelarOrdenes", Name="CancelarOrdenesFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="respuesta")]
        B2CTouresBalon.ServicioOrdenes.CancelarOrdenesResponse CancelarOrdenes(B2CTouresBalon.ServicioOrdenes.CancelarOrdenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/OrdenesTouresBalon/CancelarOrdenes", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.CancelarOrdenesResponse> CancelarOrdenesAsync(B2CTouresBalon.ServicioOrdenes.CancelarOrdenesRequest request);
        
        // CODEGEN: Parameter 'respuesta' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/OrdenesTouresBalon/CrearOrdenes", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioOrdenes.CrearOrdenesFault), Action="http://www.touresbalon.com/OrdenesTouresBalon/CrearOrdenes", Name="CrearOrdenesFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="respuesta")]
        B2CTouresBalon.ServicioOrdenes.CrearOrdenesResponse CrearOrdenes(B2CTouresBalon.ServicioOrdenes.CrearOrdenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/OrdenesTouresBalon/CrearOrdenes", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.CrearOrdenesResponse> CrearOrdenesAsync(B2CTouresBalon.ServicioOrdenes.CrearOrdenesRequest request);
        
        // CODEGEN: Parameter 'orden' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/OrdenesTouresBalon/ConsultarOrdenes", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioOrdenes.ConsultarOrdenesFault), Action="http://www.touresbalon.com/OrdenesTouresBalon/ConsultarOrdenes", Name="ConsultarOrdenesFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="orden")]
        B2CTouresBalon.ServicioOrdenes.ConsultarOrdenesResponse ConsultarOrdenes(B2CTouresBalon.ServicioOrdenes.ConsultarOrdenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/OrdenesTouresBalon/ConsultarOrdenes", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.ConsultarOrdenesResponse> ConsultarOrdenesAsync(B2CTouresBalon.ServicioOrdenes.ConsultarOrdenesRequest request);
        
        // CODEGEN: Parameter 'ordenes_cerradas' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/OrdenesTouresBalon/ConsultarRangoCerradoOrdenes", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioOrdenes.ConsultarRangoCerradoOrdenesFault), Action="http://www.touresbalon.com/OrdenesTouresBalon/ConsultarRangoCerradoOrdenes", Name="ConsultarRangoCerradoOrdenesFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ordenes_cerradas")]
        B2CTouresBalon.ServicioOrdenes.ConsultarRangoCerradoOrdenesResponse ConsultarRangoCerradoOrdenes(B2CTouresBalon.ServicioOrdenes.ConsultarRangoCerradoOrdenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/OrdenesTouresBalon/ConsultarRangoCerradoOrdenes", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.ConsultarRangoCerradoOrdenesResponse> ConsultarRangoCerradoOrdenesAsync(B2CTouresBalon.ServicioOrdenes.ConsultarRangoCerradoOrdenesRequest request);
        
        // CODEGEN: Parameter 'ordenes' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/OrdenesTouresBalon/ConsultarRankingAbiertasOrdenes", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioOrdenes.ConsultarRankingAbiertasOrdenesFault), Action="http://www.touresbalon.com/OrdenesTouresBalon/ConsultarRankingAbiertasOrdenes", Name="ConsultarRankingAbiertasOrdenesFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ordenes")]
        B2CTouresBalon.ServicioOrdenes.ConsultarRankingAbiertasOrdenesResponse ConsultarRankingAbiertasOrdenes(B2CTouresBalon.ServicioOrdenes.ConsultarRankingAbiertasOrdenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/OrdenesTouresBalon/ConsultarRankingAbiertasOrdenes", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.ConsultarRankingAbiertasOrdenesResponse> ConsultarRankingAbiertasOrdenesAsync(B2CTouresBalon.ServicioOrdenes.ConsultarRankingAbiertasOrdenesRequest request);
        
        // CODEGEN: Parameter 'ordenes' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/OrdenesTouresBalon/ConsultarRankingCerradoOrdenes", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioOrdenes.ConsultarRankingCerradoOrdenesFault), Action="http://www.touresbalon.com/OrdenesTouresBalon/ConsultarRankingCerradoOrdenes", Name="ConsultarRankingCerradoOrdenesFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ordenes")]
        B2CTouresBalon.ServicioOrdenes.ConsultarRankingCerradoOrdenesResponse ConsultarRankingCerradoOrdenes(B2CTouresBalon.ServicioOrdenes.ConsultarRankingCerradoOrdenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/OrdenesTouresBalon/ConsultarRankingCerradoOrdenes", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.ConsultarRankingCerradoOrdenesResponse> ConsultarRankingCerradoOrdenesAsync(B2CTouresBalon.ServicioOrdenes.ConsultarRankingCerradoOrdenesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarClientesOrdenes", WrapperNamespace="http://www.touresbalon.com/OrdenesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarClientesOrdenesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_cliente;
        
        public ConsultarClientesOrdenesRequest() {
        }
        
        public ConsultarClientesOrdenesRequest(int id_cliente) {
            this.id_cliente = id_cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarClientesOrdenesResponse", WrapperNamespace="http://www.touresbalon.com/OrdenesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarClientesOrdenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("orden", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioOrdenes.Orden[] orden;
        
        public ConsultarClientesOrdenesResponse() {
        }
        
        public ConsultarClientesOrdenesResponse(B2CTouresBalon.ServicioOrdenes.Orden[] orden) {
            this.orden = orden;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public enum RespuestaGenerica {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        KO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarOrdenes", WrapperNamespace="http://www.touresbalon.com/OrdenesTouresBalon/", IsWrapped=true)]
    public partial class CancelarOrdenesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("id_orden", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] id_orden;
        
        public CancelarOrdenesRequest() {
        }
        
        public CancelarOrdenesRequest(int[] id_orden) {
            this.id_orden = id_orden;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarOrdenesResponse", WrapperNamespace="http://www.touresbalon.com/OrdenesTouresBalon/", IsWrapped=true)]
    public partial class CancelarOrdenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioOrdenes.RespuestaGenerica respuesta;
        
        public CancelarOrdenesResponse() {
        }
        
        public CancelarOrdenesResponse(B2CTouresBalon.ServicioOrdenes.RespuestaGenerica respuesta) {
            this.respuesta = respuesta;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public partial class CrearOrdenResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RespuestaGenerica respuestaField;
        
        private int id_ordenField;
        
        private bool id_ordenFieldSpecified;
        
        private EstatusOrden estatus_ordenField;
        
        private bool estatus_ordenFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RespuestaGenerica respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_orden {
            get {
                return this.id_ordenField;
            }
            set {
                this.id_ordenField = value;
                this.RaisePropertyChanged("id_orden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_ordenSpecified {
            get {
                return this.id_ordenFieldSpecified;
            }
            set {
                this.id_ordenFieldSpecified = value;
                this.RaisePropertyChanged("id_ordenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public EstatusOrden estatus_orden {
            get {
                return this.estatus_ordenField;
            }
            set {
                this.estatus_ordenField = value;
                this.RaisePropertyChanged("estatus_orden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estatus_ordenSpecified {
            get {
                return this.estatus_ordenFieldSpecified;
            }
            set {
                this.estatus_ordenFieldSpecified = value;
                this.RaisePropertyChanged("estatus_ordenSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearOrdenes", WrapperNamespace="http://www.touresbalon.com/OrdenesTouresBalon/", IsWrapped=true)]
    public partial class CrearOrdenesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioOrdenes.Orden orden;
        
        public CrearOrdenesRequest() {
        }
        
        public CrearOrdenesRequest(B2CTouresBalon.ServicioOrdenes.Orden orden) {
            this.orden = orden;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CrearOrdenesResponse", WrapperNamespace="http://www.touresbalon.com/OrdenesTouresBalon/", IsWrapped=true)]
    public partial class CrearOrdenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioOrdenes.CrearOrdenResponse respuesta;
        
        public CrearOrdenesResponse() {
        }
        
        public CrearOrdenesResponse(B2CTouresBalon.ServicioOrdenes.CrearOrdenResponse respuesta) {
            this.respuesta = respuesta;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public partial class CriterioConsultaOrden : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TipoConsultaOrden tipo_consultaField;
        
        private int codigoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public TipoConsultaOrden tipo_consulta {
            get {
                return this.tipo_consultaField;
            }
            set {
                this.tipo_consultaField = value;
                this.RaisePropertyChanged("tipo_consulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public enum TipoConsultaOrden {
        
        /// <remarks/>
        ORDEN,
        
        /// <remarks/>
        PRODUCTO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarOrdenes", WrapperNamespace="http://www.touresbalon.com/OrdenesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarOrdenesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioOrdenes.CriterioConsultaOrden criterios;
        
        public ConsultarOrdenesRequest() {
        }
        
        public ConsultarOrdenesRequest(B2CTouresBalon.ServicioOrdenes.CriterioConsultaOrden criterios) {
            this.criterios = criterios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarOrdenesResponse", WrapperNamespace="http://www.touresbalon.com/OrdenesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarOrdenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("orden", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioOrdenes.Orden[] orden;
        
        public ConsultarOrdenesResponse() {
        }
        
        public ConsultarOrdenesResponse(B2CTouresBalon.ServicioOrdenes.Orden[] orden) {
            this.orden = orden;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/")]
    public partial class RespuestaOrdenCerrada : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ordenes_cerradasField;
        
        private double totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ordenes_cerradas {
            get {
                return this.ordenes_cerradasField;
            }
            set {
                this.ordenes_cerradasField = value;
                this.RaisePropertyChanged("ordenes_cerradas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarRangoCerradoOrdenes", WrapperNamespace="http://www.touresbalon.com/OrdenesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarRangoCerradoOrdenesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_inicial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_final;
        
        public ConsultarRangoCerradoOrdenesRequest() {
        }
        
        public ConsultarRangoCerradoOrdenesRequest(System.DateTime fecha_inicial, System.DateTime fecha_final) {
            this.fecha_inicial = fecha_inicial;
            this.fecha_final = fecha_final;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarRangoCerradoOrdenesResponse", WrapperNamespace="http://www.touresbalon.com/OrdenesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarRangoCerradoOrdenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioOrdenes.RespuestaOrdenCerrada ordenes_cerradas;
        
        public ConsultarRangoCerradoOrdenesResponse() {
        }
        
        public ConsultarRangoCerradoOrdenesResponse(B2CTouresBalon.ServicioOrdenes.RespuestaOrdenCerrada ordenes_cerradas) {
            this.ordenes_cerradas = ordenes_cerradas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarRankingAbiertasOrdenes", WrapperNamespace="http://www.touresbalon.com/OrdenesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarRankingAbiertasOrdenesRequest {
        
        public ConsultarRankingAbiertasOrdenesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarRankingAbiertasOrdenesResponse", WrapperNamespace="http://www.touresbalon.com/OrdenesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarRankingAbiertasOrdenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ordenes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioOrdenes.Orden[] ordenes;
        
        public ConsultarRankingAbiertasOrdenesResponse() {
        }
        
        public ConsultarRankingAbiertasOrdenesResponse(B2CTouresBalon.ServicioOrdenes.Orden[] ordenes) {
            this.ordenes = ordenes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarRankingCerradoOrdenes", WrapperNamespace="http://www.touresbalon.com/OrdenesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarRankingCerradoOrdenesRequest {
        
        public ConsultarRankingCerradoOrdenesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarRankingCerradoOrdenesResponse", WrapperNamespace="http://www.touresbalon.com/OrdenesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarRankingCerradoOrdenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/OrdenesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ordenes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioOrdenes.Orden[] ordenes;
        
        public ConsultarRankingCerradoOrdenesResponse() {
        }
        
        public ConsultarRankingCerradoOrdenesResponse(B2CTouresBalon.ServicioOrdenes.Orden[] ordenes) {
            this.ordenes = ordenes;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdenesTouresBalonChannel : B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenesTouresBalonClient : System.ServiceModel.ClientBase<B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon>, B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon {
        
        public OrdenesTouresBalonClient() {
        }
        
        public OrdenesTouresBalonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenesTouresBalonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenesTouresBalonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenesTouresBalonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioOrdenes.ConsultarClientesOrdenesResponse B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon.ConsultarClientesOrdenes(B2CTouresBalon.ServicioOrdenes.ConsultarClientesOrdenesRequest request) {
            return base.Channel.ConsultarClientesOrdenes(request);
        }
        
        public B2CTouresBalon.ServicioOrdenes.Orden[] ConsultarClientesOrdenes(int id_cliente) {
            B2CTouresBalon.ServicioOrdenes.ConsultarClientesOrdenesRequest inValue = new B2CTouresBalon.ServicioOrdenes.ConsultarClientesOrdenesRequest();
            inValue.id_cliente = id_cliente;
            B2CTouresBalon.ServicioOrdenes.ConsultarClientesOrdenesResponse retVal = ((B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon)(this)).ConsultarClientesOrdenes(inValue);
            return retVal.orden;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.ConsultarClientesOrdenesResponse> B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon.ConsultarClientesOrdenesAsync(B2CTouresBalon.ServicioOrdenes.ConsultarClientesOrdenesRequest request) {
            return base.Channel.ConsultarClientesOrdenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.ConsultarClientesOrdenesResponse> ConsultarClientesOrdenesAsync(int id_cliente) {
            B2CTouresBalon.ServicioOrdenes.ConsultarClientesOrdenesRequest inValue = new B2CTouresBalon.ServicioOrdenes.ConsultarClientesOrdenesRequest();
            inValue.id_cliente = id_cliente;
            return ((B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon)(this)).ConsultarClientesOrdenesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioOrdenes.CancelarOrdenesResponse B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon.CancelarOrdenes(B2CTouresBalon.ServicioOrdenes.CancelarOrdenesRequest request) {
            return base.Channel.CancelarOrdenes(request);
        }
        
        public B2CTouresBalon.ServicioOrdenes.RespuestaGenerica CancelarOrdenes(int[] id_orden) {
            B2CTouresBalon.ServicioOrdenes.CancelarOrdenesRequest inValue = new B2CTouresBalon.ServicioOrdenes.CancelarOrdenesRequest();
            inValue.id_orden = id_orden;
            B2CTouresBalon.ServicioOrdenes.CancelarOrdenesResponse retVal = ((B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon)(this)).CancelarOrdenes(inValue);
            return retVal.respuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.CancelarOrdenesResponse> B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon.CancelarOrdenesAsync(B2CTouresBalon.ServicioOrdenes.CancelarOrdenesRequest request) {
            return base.Channel.CancelarOrdenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.CancelarOrdenesResponse> CancelarOrdenesAsync(int[] id_orden) {
            B2CTouresBalon.ServicioOrdenes.CancelarOrdenesRequest inValue = new B2CTouresBalon.ServicioOrdenes.CancelarOrdenesRequest();
            inValue.id_orden = id_orden;
            return ((B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon)(this)).CancelarOrdenesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioOrdenes.CrearOrdenesResponse B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon.CrearOrdenes(B2CTouresBalon.ServicioOrdenes.CrearOrdenesRequest request) {
            return base.Channel.CrearOrdenes(request);
        }
        
        public B2CTouresBalon.ServicioOrdenes.CrearOrdenResponse CrearOrdenes(B2CTouresBalon.ServicioOrdenes.Orden orden) {
            B2CTouresBalon.ServicioOrdenes.CrearOrdenesRequest inValue = new B2CTouresBalon.ServicioOrdenes.CrearOrdenesRequest();
            inValue.orden = orden;
            B2CTouresBalon.ServicioOrdenes.CrearOrdenesResponse retVal = ((B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon)(this)).CrearOrdenes(inValue);
            return retVal.respuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.CrearOrdenesResponse> B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon.CrearOrdenesAsync(B2CTouresBalon.ServicioOrdenes.CrearOrdenesRequest request) {
            return base.Channel.CrearOrdenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.CrearOrdenesResponse> CrearOrdenesAsync(B2CTouresBalon.ServicioOrdenes.Orden orden) {
            B2CTouresBalon.ServicioOrdenes.CrearOrdenesRequest inValue = new B2CTouresBalon.ServicioOrdenes.CrearOrdenesRequest();
            inValue.orden = orden;
            return ((B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon)(this)).CrearOrdenesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioOrdenes.ConsultarOrdenesResponse B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon.ConsultarOrdenes(B2CTouresBalon.ServicioOrdenes.ConsultarOrdenesRequest request) {
            return base.Channel.ConsultarOrdenes(request);
        }
        
        public B2CTouresBalon.ServicioOrdenes.Orden[] ConsultarOrdenes(B2CTouresBalon.ServicioOrdenes.CriterioConsultaOrden criterios) {
            B2CTouresBalon.ServicioOrdenes.ConsultarOrdenesRequest inValue = new B2CTouresBalon.ServicioOrdenes.ConsultarOrdenesRequest();
            inValue.criterios = criterios;
            B2CTouresBalon.ServicioOrdenes.ConsultarOrdenesResponse retVal = ((B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon)(this)).ConsultarOrdenes(inValue);
            return retVal.orden;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.ConsultarOrdenesResponse> B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon.ConsultarOrdenesAsync(B2CTouresBalon.ServicioOrdenes.ConsultarOrdenesRequest request) {
            return base.Channel.ConsultarOrdenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.ConsultarOrdenesResponse> ConsultarOrdenesAsync(B2CTouresBalon.ServicioOrdenes.CriterioConsultaOrden criterios) {
            B2CTouresBalon.ServicioOrdenes.ConsultarOrdenesRequest inValue = new B2CTouresBalon.ServicioOrdenes.ConsultarOrdenesRequest();
            inValue.criterios = criterios;
            return ((B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon)(this)).ConsultarOrdenesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioOrdenes.ConsultarRangoCerradoOrdenesResponse B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon.ConsultarRangoCerradoOrdenes(B2CTouresBalon.ServicioOrdenes.ConsultarRangoCerradoOrdenesRequest request) {
            return base.Channel.ConsultarRangoCerradoOrdenes(request);
        }
        
        public B2CTouresBalon.ServicioOrdenes.RespuestaOrdenCerrada ConsultarRangoCerradoOrdenes(System.DateTime fecha_inicial, System.DateTime fecha_final) {
            B2CTouresBalon.ServicioOrdenes.ConsultarRangoCerradoOrdenesRequest inValue = new B2CTouresBalon.ServicioOrdenes.ConsultarRangoCerradoOrdenesRequest();
            inValue.fecha_inicial = fecha_inicial;
            inValue.fecha_final = fecha_final;
            B2CTouresBalon.ServicioOrdenes.ConsultarRangoCerradoOrdenesResponse retVal = ((B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon)(this)).ConsultarRangoCerradoOrdenes(inValue);
            return retVal.ordenes_cerradas;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.ConsultarRangoCerradoOrdenesResponse> B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon.ConsultarRangoCerradoOrdenesAsync(B2CTouresBalon.ServicioOrdenes.ConsultarRangoCerradoOrdenesRequest request) {
            return base.Channel.ConsultarRangoCerradoOrdenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.ConsultarRangoCerradoOrdenesResponse> ConsultarRangoCerradoOrdenesAsync(System.DateTime fecha_inicial, System.DateTime fecha_final) {
            B2CTouresBalon.ServicioOrdenes.ConsultarRangoCerradoOrdenesRequest inValue = new B2CTouresBalon.ServicioOrdenes.ConsultarRangoCerradoOrdenesRequest();
            inValue.fecha_inicial = fecha_inicial;
            inValue.fecha_final = fecha_final;
            return ((B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon)(this)).ConsultarRangoCerradoOrdenesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioOrdenes.ConsultarRankingAbiertasOrdenesResponse B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon.ConsultarRankingAbiertasOrdenes(B2CTouresBalon.ServicioOrdenes.ConsultarRankingAbiertasOrdenesRequest request) {
            return base.Channel.ConsultarRankingAbiertasOrdenes(request);
        }
        
        public B2CTouresBalon.ServicioOrdenes.Orden[] ConsultarRankingAbiertasOrdenes() {
            B2CTouresBalon.ServicioOrdenes.ConsultarRankingAbiertasOrdenesRequest inValue = new B2CTouresBalon.ServicioOrdenes.ConsultarRankingAbiertasOrdenesRequest();
            B2CTouresBalon.ServicioOrdenes.ConsultarRankingAbiertasOrdenesResponse retVal = ((B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon)(this)).ConsultarRankingAbiertasOrdenes(inValue);
            return retVal.ordenes;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.ConsultarRankingAbiertasOrdenesResponse> B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon.ConsultarRankingAbiertasOrdenesAsync(B2CTouresBalon.ServicioOrdenes.ConsultarRankingAbiertasOrdenesRequest request) {
            return base.Channel.ConsultarRankingAbiertasOrdenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.ConsultarRankingAbiertasOrdenesResponse> ConsultarRankingAbiertasOrdenesAsync() {
            B2CTouresBalon.ServicioOrdenes.ConsultarRankingAbiertasOrdenesRequest inValue = new B2CTouresBalon.ServicioOrdenes.ConsultarRankingAbiertasOrdenesRequest();
            return ((B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon)(this)).ConsultarRankingAbiertasOrdenesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioOrdenes.ConsultarRankingCerradoOrdenesResponse B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon.ConsultarRankingCerradoOrdenes(B2CTouresBalon.ServicioOrdenes.ConsultarRankingCerradoOrdenesRequest request) {
            return base.Channel.ConsultarRankingCerradoOrdenes(request);
        }
        
        public B2CTouresBalon.ServicioOrdenes.Orden[] ConsultarRankingCerradoOrdenes() {
            B2CTouresBalon.ServicioOrdenes.ConsultarRankingCerradoOrdenesRequest inValue = new B2CTouresBalon.ServicioOrdenes.ConsultarRankingCerradoOrdenesRequest();
            B2CTouresBalon.ServicioOrdenes.ConsultarRankingCerradoOrdenesResponse retVal = ((B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon)(this)).ConsultarRankingCerradoOrdenes(inValue);
            return retVal.ordenes;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.ConsultarRankingCerradoOrdenesResponse> B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon.ConsultarRankingCerradoOrdenesAsync(B2CTouresBalon.ServicioOrdenes.ConsultarRankingCerradoOrdenesRequest request) {
            return base.Channel.ConsultarRankingCerradoOrdenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioOrdenes.ConsultarRankingCerradoOrdenesResponse> ConsultarRankingCerradoOrdenesAsync() {
            B2CTouresBalon.ServicioOrdenes.ConsultarRankingCerradoOrdenesRequest inValue = new B2CTouresBalon.ServicioOrdenes.ConsultarRankingCerradoOrdenesRequest();
            return ((B2CTouresBalon.ServicioOrdenes.OrdenesTouresBalon)(this)).ConsultarRankingCerradoOrdenesAsync(inValue);
        }
    }
}
