//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2CTouresBalon.ServicioProductos {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class ConsultarProductoFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error consultarProductoFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarProductoFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ConsultarProductoFault1 {
            get {
                return this.consultarProductoFault1Field;
            }
            set {
                this.consultarProductoFault1Field = value;
                this.RaisePropertyChanged("ConsultarProductoFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class TarifaValores : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nombre_tipoField;
        
        private double precioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre_tipo {
            get {
                return this.nombre_tipoField;
            }
            set {
                this.nombre_tipoField = value;
                this.RaisePropertyChanged("nombre_tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class Ciudad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_ciudadField;
        
        private bool id_ciudadFieldSpecified;
        
        private string paisField;
        
        private TarifaValores[] tipo_ciudadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id_ciudad {
            get {
                return this.id_ciudadField;
            }
            set {
                this.id_ciudadField = value;
                this.RaisePropertyChanged("id_ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_ciudadSpecified {
            get {
                return this.id_ciudadFieldSpecified;
            }
            set {
                this.id_ciudadFieldSpecified = value;
                this.RaisePropertyChanged("id_ciudadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tipo_ciudad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public TarifaValores[] tipo_ciudad {
            get {
                return this.tipo_ciudadField;
            }
            set {
                this.tipo_ciudadField = value;
                this.RaisePropertyChanged("tipo_ciudad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class Producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_productoField;
        
        private string espectaculoField;
        
        private string descripcionField;
        
        private Ciudad ciudad_espectaculoField;
        
        private System.DateTime fecha_llegadaField;
        
        private bool fecha_llegadaFieldSpecified;
        
        private System.DateTime fecha_salidaField;
        
        private bool fecha_salidaFieldSpecified;
        
        private System.DateTime fecha_espectaculoField;
        
        private bool fecha_espectaculoFieldSpecified;
        
        private TarifaValores tipo_transporteField;
        
        private TarifaValores tipo_espectaculoField;
        
        private TarifaValores tipo_hospedajeField;
        
        private string imagen_productoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id_producto {
            get {
                return this.id_productoField;
            }
            set {
                this.id_productoField = value;
                this.RaisePropertyChanged("id_producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string espectaculo {
            get {
                return this.espectaculoField;
            }
            set {
                this.espectaculoField = value;
                this.RaisePropertyChanged("espectaculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Ciudad ciudad_espectaculo {
            get {
                return this.ciudad_espectaculoField;
            }
            set {
                this.ciudad_espectaculoField = value;
                this.RaisePropertyChanged("ciudad_espectaculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fecha_llegada {
            get {
                return this.fecha_llegadaField;
            }
            set {
                this.fecha_llegadaField = value;
                this.RaisePropertyChanged("fecha_llegada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_llegadaSpecified {
            get {
                return this.fecha_llegadaFieldSpecified;
            }
            set {
                this.fecha_llegadaFieldSpecified = value;
                this.RaisePropertyChanged("fecha_llegadaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fecha_salida {
            get {
                return this.fecha_salidaField;
            }
            set {
                this.fecha_salidaField = value;
                this.RaisePropertyChanged("fecha_salida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_salidaSpecified {
            get {
                return this.fecha_salidaFieldSpecified;
            }
            set {
                this.fecha_salidaFieldSpecified = value;
                this.RaisePropertyChanged("fecha_salidaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fecha_espectaculo {
            get {
                return this.fecha_espectaculoField;
            }
            set {
                this.fecha_espectaculoField = value;
                this.RaisePropertyChanged("fecha_espectaculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fecha_espectaculoSpecified {
            get {
                return this.fecha_espectaculoFieldSpecified;
            }
            set {
                this.fecha_espectaculoFieldSpecified = value;
                this.RaisePropertyChanged("fecha_espectaculoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public TarifaValores tipo_transporte {
            get {
                return this.tipo_transporteField;
            }
            set {
                this.tipo_transporteField = value;
                this.RaisePropertyChanged("tipo_transporte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public TarifaValores tipo_espectaculo {
            get {
                return this.tipo_espectaculoField;
            }
            set {
                this.tipo_espectaculoField = value;
                this.RaisePropertyChanged("tipo_espectaculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public TarifaValores tipo_hospedaje {
            get {
                return this.tipo_hospedajeField;
            }
            set {
                this.tipo_hospedajeField = value;
                this.RaisePropertyChanged("tipo_hospedaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string imagen_producto {
            get {
                return this.imagen_productoField;
            }
            set {
                this.imagen_productoField = value;
                this.RaisePropertyChanged("imagen_producto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class ConsultarCampaniaProductoFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error consultarCampaniaProductoFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarCampaniaProductoFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ConsultarCampaniaProductoFault1 {
            get {
                return this.consultarCampaniaProductoFault1Field;
            }
            set {
                this.consultarCampaniaProductoFault1Field = value;
                this.RaisePropertyChanged("ConsultarCampaniaProductoFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class ConsultarPorEspectaculoProductoFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error consultarPorEspectaculoProductoFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarPorEspectaculoProductoFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ConsultarPorEspectaculoProductoFault1 {
            get {
                return this.consultarPorEspectaculoProductoFault1Field;
            }
            set {
                this.consultarPorEspectaculoProductoFault1Field = value;
                this.RaisePropertyChanged("ConsultarPorEspectaculoProductoFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class ConsultarRankingEspectaculosVendidosProductoFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error consultarRankingEspectaculosVendidosProductoFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarRankingEspectaculosVendidosProductoFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ConsultarRankingEspectaculosVendidosProductoFault1 {
            get {
                return this.consultarRankingEspectaculosVendidosProductoFault1Field;
            }
            set {
                this.consultarRankingEspectaculosVendidosProductoFault1Field = value;
                this.RaisePropertyChanged("ConsultarRankingEspectaculosVendidosProductoFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class ConsultarRankingFechaProductoFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error consultarRankingFechaProductoFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarRankingFechaProductoFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ConsultarRankingFechaProductoFault1 {
            get {
                return this.consultarRankingFechaProductoFault1Field;
            }
            set {
                this.consultarRankingFechaProductoFault1Field = value;
                this.RaisePropertyChanged("ConsultarRankingFechaProductoFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class GestionCampaniaProductoFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error gestionCampañaProductoFaultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error GestionCampañaProductoFault {
            get {
                return this.gestionCampañaProductoFaultField;
            }
            set {
                this.gestionCampañaProductoFaultField = value;
                this.RaisePropertyChanged("GestionCampañaProductoFault");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class GestionProductoFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error gestionProductoFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GestionProductoFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error GestionProductoFault1 {
            get {
                return this.gestionProductoFault1Field;
            }
            set {
                this.gestionProductoFault1Field = value;
                this.RaisePropertyChanged("GestionProductoFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class GestionTarifaFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error gestionTarifaFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GestionTarifaFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error GestionTarifaFault1 {
            get {
                return this.gestionTarifaFault1Field;
            }
            set {
                this.gestionTarifaFault1Field = value;
                this.RaisePropertyChanged("GestionTarifaFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class ConsultaTop5ProductosFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error consultaTop5ProductosFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultaTop5ProductosFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ConsultaTop5ProductosFault1 {
            get {
                return this.consultaTop5ProductosFault1Field;
            }
            set {
                this.consultaTop5ProductosFault1Field = value;
                this.RaisePropertyChanged("ConsultaTop5ProductosFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", ConfigurationName="ServicioProductos.ProductosTouresBalon")]
    public interface ProductosTouresBalon {
        
        // CODEGEN: Parameter 'productos' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultarProducto", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioProductos.ConsultarProductoFault), Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultarProducto", Name="ConsultarProductoFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productos")]
        B2CTouresBalon.ServicioProductos.ConsultarProductoResponse ConsultarProducto(B2CTouresBalon.ServicioProductos.ConsultarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultarProductoResponse> ConsultarProductoAsync(B2CTouresBalon.ServicioProductos.ConsultarProductoRequest request);
        
        // CODEGEN: Parameter 'productos' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultarCampaniaProducto", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioProductos.ConsultarCampaniaProductoFault), Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultarCampaniaProducto", Name="ConsultarCampaniaProductoFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productos")]
        B2CTouresBalon.ServicioProductos.ConsultarCampaniaProductoResponse ConsultarCampaniaProducto(B2CTouresBalon.ServicioProductos.ConsultarCampaniaProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultarCampaniaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultarCampaniaProductoResponse> ConsultarCampaniaProductoAsync(B2CTouresBalon.ServicioProductos.ConsultarCampaniaProductoRequest request);
        
        // CODEGEN: Parameter 'productos' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultarPorEspectaculoProducto", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioProductos.ConsultarPorEspectaculoProductoFault), Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultarPorEspectaculoProducto", Name="ConsultarPorEspectaculoProductoFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productos")]
        B2CTouresBalon.ServicioProductos.ConsultarPorEspectaculoProductoResponse ConsultarPorEspectaculoProducto(B2CTouresBalon.ServicioProductos.ConsultarPorEspectaculoProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultarPorEspectaculoProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultarPorEspectaculoProductoResponse> ConsultarPorEspectaculoProductoAsync(B2CTouresBalon.ServicioProductos.ConsultarPorEspectaculoProductoRequest request);
        
        // CODEGEN: Parameter 'tipo_espectaculo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultarRankingEspectaculosVendi" +
            "dosProducto", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioProductos.ConsultarRankingEspectaculosVendidosProductoFault), Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultarRankingEspectaculosVendi" +
            "dosProducto", Name="ConsultarRankingEspectaculosVendidosProductoFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="tipo_espectaculo")]
        B2CTouresBalon.ServicioProductos.ConsultarRankingEspectaculosVendidosProductoResponse ConsultarRankingEspectaculosVendidosProducto(B2CTouresBalon.ServicioProductos.ConsultarRankingEspectaculosVendidosProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultarRankingEspectaculosVendi" +
            "dosProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultarRankingEspectaculosVendidosProductoResponse> ConsultarRankingEspectaculosVendidosProductoAsync(B2CTouresBalon.ServicioProductos.ConsultarRankingEspectaculosVendidosProductoRequest request);
        
        // CODEGEN: Parameter 'productos' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultarRankingFechaProducto", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioProductos.ConsultarRankingFechaProductoFault), Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultarRankingFechaProducto", Name="ConsultarRankingFechaProductoFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="productos")]
        B2CTouresBalon.ServicioProductos.ConsultarRankingFechaProductoResponse ConsultarRankingFechaProducto(B2CTouresBalon.ServicioProductos.ConsultarRankingFechaProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultarRankingFechaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultarRankingFechaProductoResponse> ConsultarRankingFechaProductoAsync(B2CTouresBalon.ServicioProductos.ConsultarRankingFechaProductoRequest request);
        
        // CODEGEN: Parameter 'gestioncampaniaResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/GestionCampaniaProducto", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioProductos.GestionCampaniaProductoFault), Action="http://www.touresbalon.com/ProductosTouresBalon/GestionCampaniaProducto", Name="GestionCampaniaProductoFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="gestioncampaniaResponse")]
        B2CTouresBalon.ServicioProductos.GestionCampaniaProductoResponse GestionCampaniaProducto(B2CTouresBalon.ServicioProductos.GestionCampaniaProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/GestionCampaniaProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.GestionCampaniaProductoResponse> GestionCampaniaProductoAsync(B2CTouresBalon.ServicioProductos.GestionCampaniaProductoRequest request);
        
        // CODEGEN: Parameter 'gestion_producto_reponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/GestionProducto", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioProductos.GestionProductoFault), Action="http://www.touresbalon.com/ProductosTouresBalon/GestionProducto", Name="GestionProductoFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="gestion_producto_reponse")]
        B2CTouresBalon.ServicioProductos.GestionProductoResponse GestionProducto(B2CTouresBalon.ServicioProductos.GestionProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/GestionProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.GestionProductoResponse> GestionProductoAsync(B2CTouresBalon.ServicioProductos.GestionProductoRequest request);
        
        // CODEGEN: Parameter 'respuesta' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/GestionTarifa", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioProductos.GestionTarifaFault), Action="http://www.touresbalon.com/ProductosTouresBalon/GestionTarifa", Name="GestionTarifaFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="respuesta")]
        B2CTouresBalon.ServicioProductos.GestionTarifaResponse GestionTarifa(B2CTouresBalon.ServicioProductos.GestionTarifaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/GestionTarifa", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.GestionTarifaResponse> GestionTarifaAsync(B2CTouresBalon.ServicioProductos.GestionTarifaRequest request);
        
        // CODEGEN: Parameter 'lista_productos_top' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultaTop5Productos", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioProductos.ConsultaTop5ProductosFault), Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultaTop5Productos", Name="ConsultaTop5ProductosFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="lista_productos_top")]
        B2CTouresBalon.ServicioProductos.ConsultaTop5ProductosResponse ConsultaTop5Productos(B2CTouresBalon.ServicioProductos.ConsultaTop5ProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ProductosTouresBalon/ConsultaTop5Productos", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultaTop5ProductosResponse> ConsultaTop5ProductosAsync(B2CTouresBalon.ServicioProductos.ConsultaTop5ProductosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public enum TipoConsultaProducto {
        
        /// <remarks/>
        NOMBRE,
        
        /// <remarks/>
        DESCRIPCION,
        
        /// <remarks/>
        ID,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarProducto", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class ConsultarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.TipoConsultaProducto tipo_consulta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cadena_consulta;
        
        public ConsultarProductoRequest() {
        }
        
        public ConsultarProductoRequest(B2CTouresBalon.ServicioProductos.TipoConsultaProducto tipo_consulta, string cadena_consulta) {
            this.tipo_consulta = tipo_consulta;
            this.cadena_consulta = cadena_consulta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarProductoResponse", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class ConsultarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("productos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.Producto[] productos;
        
        public ConsultarProductoResponse() {
        }
        
        public ConsultarProductoResponse(B2CTouresBalon.ServicioProductos.Producto[] productos) {
            this.productos = productos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarCampaniaProducto", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class ConsultarCampaniaProductoRequest {
        
        public ConsultarCampaniaProductoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarCampaniaProductoResponse", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class ConsultarCampaniaProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("productos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.Producto[] productos;
        
        public ConsultarCampaniaProductoResponse() {
        }
        
        public ConsultarCampaniaProductoResponse(B2CTouresBalon.ServicioProductos.Producto[] productos) {
            this.productos = productos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorEspectaculoProducto", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class ConsultarPorEspectaculoProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string espectaculo;
        
        public ConsultarPorEspectaculoProductoRequest() {
        }
        
        public ConsultarPorEspectaculoProductoRequest(string espectaculo) {
            this.espectaculo = espectaculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorEspectaculoProductoResponse", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class ConsultarPorEspectaculoProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("productos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.Producto[] productos;
        
        public ConsultarPorEspectaculoProductoResponse() {
        }
        
        public ConsultarPorEspectaculoProductoResponse(B2CTouresBalon.ServicioProductos.Producto[] productos) {
            this.productos = productos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarRankingEspectaculosVendidosProducto", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class ConsultarRankingEspectaculosVendidosProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_inicial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_fin;
        
        public ConsultarRankingEspectaculosVendidosProductoRequest() {
        }
        
        public ConsultarRankingEspectaculosVendidosProductoRequest(System.DateTime fecha_inicial, System.DateTime fecha_fin) {
            this.fecha_inicial = fecha_inicial;
            this.fecha_fin = fecha_fin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarRankingEspectaculosVendidosProductoResponse", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class ConsultarRankingEspectaculosVendidosProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("tipo_espectaculo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.TarifaValores[] tipo_espectaculo;
        
        public ConsultarRankingEspectaculosVendidosProductoResponse() {
        }
        
        public ConsultarRankingEspectaculosVendidosProductoResponse(B2CTouresBalon.ServicioProductos.TarifaValores[] tipo_espectaculo) {
            this.tipo_espectaculo = tipo_espectaculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarRankingFechaProducto", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class ConsultarRankingFechaProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_inicial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_fin;
        
        public ConsultarRankingFechaProductoRequest() {
        }
        
        public ConsultarRankingFechaProductoRequest(System.DateTime fecha_inicial, System.DateTime fecha_fin) {
            this.fecha_inicial = fecha_inicial;
            this.fecha_fin = fecha_fin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarRankingFechaProductoResponse", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class ConsultarRankingFechaProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("productos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.Producto[] productos;
        
        public ConsultarRankingFechaProductoResponse() {
        }
        
        public ConsultarRankingFechaProductoResponse(B2CTouresBalon.ServicioProductos.Producto[] productos) {
            this.productos = productos;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public enum TipoAccion {
        
        /// <remarks/>
        ADICIONAR,
        
        /// <remarks/>
        ELIMINAR,
        
        /// <remarks/>
        MODIFICAR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class Campania : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Producto id_productoField;
        
        private System.DateTime fecha_inicio_campaniaField;
        
        private System.DateTime fecha_fin_campaniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Producto id_producto {
            get {
                return this.id_productoField;
            }
            set {
                this.id_productoField = value;
                this.RaisePropertyChanged("id_producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fecha_inicio_campania {
            get {
                return this.fecha_inicio_campaniaField;
            }
            set {
                this.fecha_inicio_campaniaField = value;
                this.RaisePropertyChanged("fecha_inicio_campania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fecha_fin_campania {
            get {
                return this.fecha_fin_campaniaField;
            }
            set {
                this.fecha_fin_campaniaField = value;
                this.RaisePropertyChanged("fecha_fin_campania");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class TipoGestionCampaniaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RespuestaGenerica respuestaField;
        
        private int id_campaniaField;
        
        private bool id_campaniaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RespuestaGenerica respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_campania {
            get {
                return this.id_campaniaField;
            }
            set {
                this.id_campaniaField = value;
                this.RaisePropertyChanged("id_campania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_campaniaSpecified {
            get {
                return this.id_campaniaFieldSpecified;
            }
            set {
                this.id_campaniaFieldSpecified = value;
                this.RaisePropertyChanged("id_campaniaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public enum RespuestaGenerica {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        KO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GestionCampaniaProducto", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class GestionCampaniaProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.TipoAccion tipo_operacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.Campania campania;
        
        public GestionCampaniaProductoRequest() {
        }
        
        public GestionCampaniaProductoRequest(B2CTouresBalon.ServicioProductos.TipoAccion tipo_operacion, B2CTouresBalon.ServicioProductos.Campania campania) {
            this.tipo_operacion = tipo_operacion;
            this.campania = campania;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GestionCampaniaProductoResponse", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class GestionCampaniaProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.TipoGestionCampaniaResponse gestioncampaniaResponse;
        
        public GestionCampaniaProductoResponse() {
        }
        
        public GestionCampaniaProductoResponse(B2CTouresBalon.ServicioProductos.TipoGestionCampaniaResponse gestioncampaniaResponse) {
            this.gestioncampaniaResponse = gestioncampaniaResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class TipoGestionProductoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RespuestaGenerica respuestaField;
        
        private int id_productoField;
        
        private bool id_productoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RespuestaGenerica respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_producto {
            get {
                return this.id_productoField;
            }
            set {
                this.id_productoField = value;
                this.RaisePropertyChanged("id_producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_productoSpecified {
            get {
                return this.id_productoFieldSpecified;
            }
            set {
                this.id_productoFieldSpecified = value;
                this.RaisePropertyChanged("id_productoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GestionProducto", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class GestionProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.TipoAccion tipo_operacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.Producto producto;
        
        public GestionProductoRequest() {
        }
        
        public GestionProductoRequest(B2CTouresBalon.ServicioProductos.TipoAccion tipo_operacion, B2CTouresBalon.ServicioProductos.Producto producto) {
            this.tipo_operacion = tipo_operacion;
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GestionProductoResponse", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class GestionProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.TipoGestionProductoResponse gestion_producto_reponse;
        
        public GestionProductoResponse() {
        }
        
        public GestionProductoResponse(B2CTouresBalon.ServicioProductos.TipoGestionProductoResponse gestion_producto_reponse) {
            this.gestion_producto_reponse = gestion_producto_reponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public enum TipoTarifa {
        
        /// <remarks/>
        TRANSPORTE,
        
        /// <remarks/>
        HOSPEDAJE,
        
        /// <remarks/>
        ESPECTACULO,
        
        /// <remarks/>
        CIUDAD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/")]
    public partial class TipoGestionTarifaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RespuestaGenerica respuestaField;
        
        private TipoTarifa tarifaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RespuestaGenerica respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public TipoTarifa tarifa {
            get {
                return this.tarifaField;
            }
            set {
                this.tarifaField = value;
                this.RaisePropertyChanged("tarifa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            var propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GestionTarifa", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class GestionTarifaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.TipoAccion tipo_operacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.TipoTarifa tipo_tarifa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.TarifaValores tarifa;
        
        public GestionTarifaRequest() {
        }
        
        public GestionTarifaRequest(B2CTouresBalon.ServicioProductos.TipoAccion tipo_operacion, B2CTouresBalon.ServicioProductos.TipoTarifa tipo_tarifa, B2CTouresBalon.ServicioProductos.TarifaValores tarifa) {
            this.tipo_operacion = tipo_operacion;
            this.tipo_tarifa = tipo_tarifa;
            this.tarifa = tarifa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GestionTarifaResponse", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class GestionTarifaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.TipoGestionTarifaResponse respuesta;
        
        public GestionTarifaResponse() {
        }
        
        public GestionTarifaResponse(B2CTouresBalon.ServicioProductos.TipoGestionTarifaResponse respuesta) {
            this.respuesta = respuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaTop5Productos", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class ConsultaTop5ProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("id_producto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] id_producto;
        
        public ConsultaTop5ProductosRequest() {
        }
        
        public ConsultaTop5ProductosRequest(int[] id_producto) {
            this.id_producto = id_producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaTop5ProductosResponse", WrapperNamespace="http://www.touresbalon.com/ProductosTouresBalon/", IsWrapped=true)]
    public partial class ConsultaTop5ProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ProductosTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("lista_productos_top", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioProductos.Producto[] lista_productos_top;
        
        public ConsultaTop5ProductosResponse() {
        }
        
        public ConsultaTop5ProductosResponse(B2CTouresBalon.ServicioProductos.Producto[] lista_productos_top) {
            this.lista_productos_top = lista_productos_top;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductosTouresBalonChannel : B2CTouresBalon.ServicioProductos.ProductosTouresBalon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosTouresBalonClient : System.ServiceModel.ClientBase<B2CTouresBalon.ServicioProductos.ProductosTouresBalon>, B2CTouresBalon.ServicioProductos.ProductosTouresBalon {
        
        public ProductosTouresBalonClient() {
        }
        
        public ProductosTouresBalonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductosTouresBalonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosTouresBalonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosTouresBalonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioProductos.ConsultarProductoResponse B2CTouresBalon.ServicioProductos.ProductosTouresBalon.ConsultarProducto(B2CTouresBalon.ServicioProductos.ConsultarProductoRequest request) {
            return base.Channel.ConsultarProducto(request);
        }
        
        public B2CTouresBalon.ServicioProductos.Producto[] ConsultarProducto(B2CTouresBalon.ServicioProductos.TipoConsultaProducto tipo_consulta, string cadena_consulta) {
            var inValue = new B2CTouresBalon.ServicioProductos.ConsultarProductoRequest();
            inValue.tipo_consulta = tipo_consulta;
            inValue.cadena_consulta = cadena_consulta;
            var retVal = ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).ConsultarProducto(inValue);
            return retVal.productos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultarProductoResponse> B2CTouresBalon.ServicioProductos.ProductosTouresBalon.ConsultarProductoAsync(B2CTouresBalon.ServicioProductos.ConsultarProductoRequest request) {
            return base.Channel.ConsultarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultarProductoResponse> ConsultarProductoAsync(B2CTouresBalon.ServicioProductos.TipoConsultaProducto tipo_consulta, string cadena_consulta) {
            var inValue = new B2CTouresBalon.ServicioProductos.ConsultarProductoRequest();
            inValue.tipo_consulta = tipo_consulta;
            inValue.cadena_consulta = cadena_consulta;
            return ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).ConsultarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioProductos.ConsultarCampaniaProductoResponse B2CTouresBalon.ServicioProductos.ProductosTouresBalon.ConsultarCampaniaProducto(B2CTouresBalon.ServicioProductos.ConsultarCampaniaProductoRequest request) {
            return base.Channel.ConsultarCampaniaProducto(request);
        }
        
        public B2CTouresBalon.ServicioProductos.Producto[] ConsultarCampaniaProducto() {
            var inValue = new B2CTouresBalon.ServicioProductos.ConsultarCampaniaProductoRequest();
            var retVal = ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).ConsultarCampaniaProducto(inValue);
            return retVal.productos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultarCampaniaProductoResponse> B2CTouresBalon.ServicioProductos.ProductosTouresBalon.ConsultarCampaniaProductoAsync(B2CTouresBalon.ServicioProductos.ConsultarCampaniaProductoRequest request) {
            return base.Channel.ConsultarCampaniaProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultarCampaniaProductoResponse> ConsultarCampaniaProductoAsync() {
            var inValue = new B2CTouresBalon.ServicioProductos.ConsultarCampaniaProductoRequest();
            return ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).ConsultarCampaniaProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioProductos.ConsultarPorEspectaculoProductoResponse B2CTouresBalon.ServicioProductos.ProductosTouresBalon.ConsultarPorEspectaculoProducto(B2CTouresBalon.ServicioProductos.ConsultarPorEspectaculoProductoRequest request) {
            return base.Channel.ConsultarPorEspectaculoProducto(request);
        }
        
        public B2CTouresBalon.ServicioProductos.Producto[] ConsultarPorEspectaculoProducto(string espectaculo) {
            var inValue = new B2CTouresBalon.ServicioProductos.ConsultarPorEspectaculoProductoRequest();
            inValue.espectaculo = espectaculo;
            var retVal = ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).ConsultarPorEspectaculoProducto(inValue);
            return retVal.productos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultarPorEspectaculoProductoResponse> B2CTouresBalon.ServicioProductos.ProductosTouresBalon.ConsultarPorEspectaculoProductoAsync(B2CTouresBalon.ServicioProductos.ConsultarPorEspectaculoProductoRequest request) {
            return base.Channel.ConsultarPorEspectaculoProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultarPorEspectaculoProductoResponse> ConsultarPorEspectaculoProductoAsync(string espectaculo) {
            var inValue = new B2CTouresBalon.ServicioProductos.ConsultarPorEspectaculoProductoRequest();
            inValue.espectaculo = espectaculo;
            return ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).ConsultarPorEspectaculoProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioProductos.ConsultarRankingEspectaculosVendidosProductoResponse B2CTouresBalon.ServicioProductos.ProductosTouresBalon.ConsultarRankingEspectaculosVendidosProducto(B2CTouresBalon.ServicioProductos.ConsultarRankingEspectaculosVendidosProductoRequest request) {
            return base.Channel.ConsultarRankingEspectaculosVendidosProducto(request);
        }
        
        public B2CTouresBalon.ServicioProductos.TarifaValores[] ConsultarRankingEspectaculosVendidosProducto(System.DateTime fecha_inicial, System.DateTime fecha_fin) {
            var inValue = new B2CTouresBalon.ServicioProductos.ConsultarRankingEspectaculosVendidosProductoRequest();
            inValue.fecha_inicial = fecha_inicial;
            inValue.fecha_fin = fecha_fin;
            var retVal = ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).ConsultarRankingEspectaculosVendidosProducto(inValue);
            return retVal.tipo_espectaculo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultarRankingEspectaculosVendidosProductoResponse> B2CTouresBalon.ServicioProductos.ProductosTouresBalon.ConsultarRankingEspectaculosVendidosProductoAsync(B2CTouresBalon.ServicioProductos.ConsultarRankingEspectaculosVendidosProductoRequest request) {
            return base.Channel.ConsultarRankingEspectaculosVendidosProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultarRankingEspectaculosVendidosProductoResponse> ConsultarRankingEspectaculosVendidosProductoAsync(System.DateTime fecha_inicial, System.DateTime fecha_fin) {
            var inValue = new B2CTouresBalon.ServicioProductos.ConsultarRankingEspectaculosVendidosProductoRequest();
            inValue.fecha_inicial = fecha_inicial;
            inValue.fecha_fin = fecha_fin;
            return ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).ConsultarRankingEspectaculosVendidosProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioProductos.ConsultarRankingFechaProductoResponse B2CTouresBalon.ServicioProductos.ProductosTouresBalon.ConsultarRankingFechaProducto(B2CTouresBalon.ServicioProductos.ConsultarRankingFechaProductoRequest request) {
            return base.Channel.ConsultarRankingFechaProducto(request);
        }
        
        public B2CTouresBalon.ServicioProductos.Producto[] ConsultarRankingFechaProducto(System.DateTime fecha_inicial, System.DateTime fecha_fin) {
            var inValue = new B2CTouresBalon.ServicioProductos.ConsultarRankingFechaProductoRequest();
            inValue.fecha_inicial = fecha_inicial;
            inValue.fecha_fin = fecha_fin;
            var retVal = ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).ConsultarRankingFechaProducto(inValue);
            return retVal.productos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultarRankingFechaProductoResponse> B2CTouresBalon.ServicioProductos.ProductosTouresBalon.ConsultarRankingFechaProductoAsync(B2CTouresBalon.ServicioProductos.ConsultarRankingFechaProductoRequest request) {
            return base.Channel.ConsultarRankingFechaProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultarRankingFechaProductoResponse> ConsultarRankingFechaProductoAsync(System.DateTime fecha_inicial, System.DateTime fecha_fin) {
            var inValue = new B2CTouresBalon.ServicioProductos.ConsultarRankingFechaProductoRequest();
            inValue.fecha_inicial = fecha_inicial;
            inValue.fecha_fin = fecha_fin;
            return ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).ConsultarRankingFechaProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioProductos.GestionCampaniaProductoResponse B2CTouresBalon.ServicioProductos.ProductosTouresBalon.GestionCampaniaProducto(B2CTouresBalon.ServicioProductos.GestionCampaniaProductoRequest request) {
            return base.Channel.GestionCampaniaProducto(request);
        }
        
        public B2CTouresBalon.ServicioProductos.TipoGestionCampaniaResponse GestionCampaniaProducto(B2CTouresBalon.ServicioProductos.TipoAccion tipo_operacion, B2CTouresBalon.ServicioProductos.Campania campania) {
            var inValue = new B2CTouresBalon.ServicioProductos.GestionCampaniaProductoRequest();
            inValue.tipo_operacion = tipo_operacion;
            inValue.campania = campania;
            var retVal = ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).GestionCampaniaProducto(inValue);
            return retVal.gestioncampaniaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.GestionCampaniaProductoResponse> B2CTouresBalon.ServicioProductos.ProductosTouresBalon.GestionCampaniaProductoAsync(B2CTouresBalon.ServicioProductos.GestionCampaniaProductoRequest request) {
            return base.Channel.GestionCampaniaProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.GestionCampaniaProductoResponse> GestionCampaniaProductoAsync(B2CTouresBalon.ServicioProductos.TipoAccion tipo_operacion, B2CTouresBalon.ServicioProductos.Campania campania) {
            var inValue = new B2CTouresBalon.ServicioProductos.GestionCampaniaProductoRequest();
            inValue.tipo_operacion = tipo_operacion;
            inValue.campania = campania;
            return ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).GestionCampaniaProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioProductos.GestionProductoResponse B2CTouresBalon.ServicioProductos.ProductosTouresBalon.GestionProducto(B2CTouresBalon.ServicioProductos.GestionProductoRequest request) {
            return base.Channel.GestionProducto(request);
        }
        
        public B2CTouresBalon.ServicioProductos.TipoGestionProductoResponse GestionProducto(B2CTouresBalon.ServicioProductos.TipoAccion tipo_operacion, B2CTouresBalon.ServicioProductos.Producto producto) {
            var inValue = new B2CTouresBalon.ServicioProductos.GestionProductoRequest();
            inValue.tipo_operacion = tipo_operacion;
            inValue.producto = producto;
            var retVal = ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).GestionProducto(inValue);
            return retVal.gestion_producto_reponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.GestionProductoResponse> B2CTouresBalon.ServicioProductos.ProductosTouresBalon.GestionProductoAsync(B2CTouresBalon.ServicioProductos.GestionProductoRequest request) {
            return base.Channel.GestionProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.GestionProductoResponse> GestionProductoAsync(B2CTouresBalon.ServicioProductos.TipoAccion tipo_operacion, B2CTouresBalon.ServicioProductos.Producto producto) {
            var inValue = new B2CTouresBalon.ServicioProductos.GestionProductoRequest();
            inValue.tipo_operacion = tipo_operacion;
            inValue.producto = producto;
            return ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).GestionProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioProductos.GestionTarifaResponse B2CTouresBalon.ServicioProductos.ProductosTouresBalon.GestionTarifa(B2CTouresBalon.ServicioProductos.GestionTarifaRequest request) {
            return base.Channel.GestionTarifa(request);
        }
        
        public B2CTouresBalon.ServicioProductos.TipoGestionTarifaResponse GestionTarifa(B2CTouresBalon.ServicioProductos.TipoAccion tipo_operacion, B2CTouresBalon.ServicioProductos.TipoTarifa tipo_tarifa, B2CTouresBalon.ServicioProductos.TarifaValores tarifa) {
            var inValue = new B2CTouresBalon.ServicioProductos.GestionTarifaRequest();
            inValue.tipo_operacion = tipo_operacion;
            inValue.tipo_tarifa = tipo_tarifa;
            inValue.tarifa = tarifa;
            var retVal = ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).GestionTarifa(inValue);
            return retVal.respuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.GestionTarifaResponse> B2CTouresBalon.ServicioProductos.ProductosTouresBalon.GestionTarifaAsync(B2CTouresBalon.ServicioProductos.GestionTarifaRequest request) {
            return base.Channel.GestionTarifaAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.GestionTarifaResponse> GestionTarifaAsync(B2CTouresBalon.ServicioProductos.TipoAccion tipo_operacion, B2CTouresBalon.ServicioProductos.TipoTarifa tipo_tarifa, B2CTouresBalon.ServicioProductos.TarifaValores tarifa) {
            var inValue = new B2CTouresBalon.ServicioProductos.GestionTarifaRequest();
            inValue.tipo_operacion = tipo_operacion;
            inValue.tipo_tarifa = tipo_tarifa;
            inValue.tarifa = tarifa;
            return ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).GestionTarifaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioProductos.ConsultaTop5ProductosResponse B2CTouresBalon.ServicioProductos.ProductosTouresBalon.ConsultaTop5Productos(B2CTouresBalon.ServicioProductos.ConsultaTop5ProductosRequest request) {
            return base.Channel.ConsultaTop5Productos(request);
        }
        
        public B2CTouresBalon.ServicioProductos.Producto[] ConsultaTop5Productos(int[] id_producto) {
            var inValue = new B2CTouresBalon.ServicioProductos.ConsultaTop5ProductosRequest();
            inValue.id_producto = id_producto;
            var retVal = ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).ConsultaTop5Productos(inValue);
            return retVal.lista_productos_top;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultaTop5ProductosResponse> B2CTouresBalon.ServicioProductos.ProductosTouresBalon.ConsultaTop5ProductosAsync(B2CTouresBalon.ServicioProductos.ConsultaTop5ProductosRequest request) {
            return base.Channel.ConsultaTop5ProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioProductos.ConsultaTop5ProductosResponse> ConsultaTop5ProductosAsync(int[] id_producto) {
            var inValue = new B2CTouresBalon.ServicioProductos.ConsultaTop5ProductosRequest();
            inValue.id_producto = id_producto;
            return ((B2CTouresBalon.ServicioProductos.ProductosTouresBalon)(this)).ConsultaTop5ProductosAsync(inValue);
        }
    }
}
