//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace DataAccess
{
    public partial class CUSTOMER
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.ORDERS = new HashSet<ORDERS>();
            this.ADDRESS = new HashSet<ADDRESS>();
        }
    
        public decimal CUSTID { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "First Name")]
        public string FNAME { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Last Name")]
        public string LNAME { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        public string PHONENUMBER { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email Adrress")]
        public string EMAIL { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string PASSWORD { get; set; }

        [DataType(DataType.Text)]
        [Display(Name = "Credit Card Type")]
        public string CREDITCARDTYPE { get; set; }

        [DataType(DataType.CreditCard)]
        [Display(Name = "Credit Card Number")]
        public string CREDITCARDNUMBER { get; set; }
        public string STATUS { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS> ORDERS { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADDRESS> ADDRESS { get; set; }
    }
}
