//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2CTouresBalon.ServicioClientes {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ClientesTouresBalon/")]
    public partial class RegistrarClienteFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error registrarClienteFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegistrarClienteFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error RegistrarClienteFault1 {
            get {
                return this.registrarClienteFault1Field;
            }
            set {
                this.registrarClienteFault1Field = value;
                this.RaisePropertyChanged("RegistrarClienteFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/")]
    public partial class RegistrarClienteReponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RespuestaGenerica respuestaField;
        
        private int id_clienteField;
        
        private bool id_clienteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RespuestaGenerica respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                this.id_clienteField = value;
                this.RaisePropertyChanged("id_cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_clienteSpecified {
            get {
                return this.id_clienteFieldSpecified;
            }
            set {
                this.id_clienteFieldSpecified = value;
                this.RaisePropertyChanged("id_clienteSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/")]
    public enum RespuestaGenerica {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        KO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/")]
    public partial class Direccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_direccionField;
        
        private bool id_direccionFieldSpecified;
        
        private string paisField;
        
        private string ciudadField;
        
        private string estadoField;
        
        private string cod_postalField;
        
        private string tipo_dirField;
        
        private string dir_calleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id_direccion {
            get {
                return this.id_direccionField;
            }
            set {
                this.id_direccionField = value;
                this.RaisePropertyChanged("id_direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_direccionSpecified {
            get {
                return this.id_direccionFieldSpecified;
            }
            set {
                this.id_direccionFieldSpecified = value;
                this.RaisePropertyChanged("id_direccionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cod_postal {
            get {
                return this.cod_postalField;
            }
            set {
                this.cod_postalField = value;
                this.RaisePropertyChanged("cod_postal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipo_dir {
            get {
                return this.tipo_dirField;
            }
            set {
                this.tipo_dirField = value;
                this.RaisePropertyChanged("tipo_dir");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string dir_calle {
            get {
                return this.dir_calleField;
            }
            set {
                this.dir_calleField = value;
                this.RaisePropertyChanged("dir_calle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/")]
    public partial class Cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_clienteField;
        
        private bool id_clienteFieldSpecified;
        
        private string nombresField;
        
        private string apellidosField;
        
        private string num_telField;
        
        private string emailField;
        
        private string contraseniaField;
        
        private string tipo_tarjetaField;
        
        private string numero_tarjetaField;
        
        private Direccion[] direccionField;
        
        private EstatusCliente estatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                this.id_clienteField = value;
                this.RaisePropertyChanged("id_cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_clienteSpecified {
            get {
                return this.id_clienteFieldSpecified;
            }
            set {
                this.id_clienteFieldSpecified = value;
                this.RaisePropertyChanged("id_clienteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string num_tel {
            get {
                return this.num_telField;
            }
            set {
                this.num_telField = value;
                this.RaisePropertyChanged("num_tel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                this.contraseniaField = value;
                this.RaisePropertyChanged("contrasenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipo_tarjeta {
            get {
                return this.tipo_tarjetaField;
            }
            set {
                this.tipo_tarjetaField = value;
                this.RaisePropertyChanged("tipo_tarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string numero_tarjeta {
            get {
                return this.numero_tarjetaField;
            }
            set {
                this.numero_tarjetaField = value;
                this.RaisePropertyChanged("numero_tarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("direccion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public Direccion[] direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public EstatusCliente estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("estatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/")]
    public enum EstatusCliente {
        
        /// <remarks/>
        PLATINO,
        
        /// <remarks/>
        DORADO,
        
        /// <remarks/>
        PLATEADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ClientesTouresBalon/")]
    public partial class AutenticarClienteFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error autenticarClienteFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AutenticarClienteFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error AutenticarClienteFault1 {
            get {
                return this.autenticarClienteFault1Field;
            }
            set {
                this.autenticarClienteFault1Field = value;
                this.RaisePropertyChanged("AutenticarClienteFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ClientesTouresBalon/")]
    public partial class ActualizarClienteFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error actualizarClienteFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActualizarClienteFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ActualizarClienteFault1 {
            get {
                return this.actualizarClienteFault1Field;
            }
            set {
                this.actualizarClienteFault1Field = value;
                this.RaisePropertyChanged("ActualizarClienteFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ClientesTouresBalon/")]
    public partial class ActualizarContraseniaClienteFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error actualizarContraseniaClienteFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActualizarContraseniaClienteFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ActualizarContraseniaClienteFault1 {
            get {
                return this.actualizarContraseniaClienteFault1Field;
            }
            set {
                this.actualizarContraseniaClienteFault1Field = value;
                this.RaisePropertyChanged("ActualizarContraseniaClienteFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ClientesTouresBalon/")]
    public partial class ActualizarEstatusClienteFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error actualizarEstatusClienteFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActualizarEstatusClienteFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ActualizarEstatusClienteFault1 {
            get {
                return this.actualizarEstatusClienteFault1Field;
            }
            set {
                this.actualizarEstatusClienteFault1Field = value;
                this.RaisePropertyChanged("ActualizarEstatusClienteFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ClientesTouresBalon/")]
    public partial class ConsultarPorIdentificacionClienteFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error consultarPorIdentificacionClienteFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarPorIdentificacionClienteFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ConsultarPorIdentificacionClienteFault1 {
            get {
                return this.consultarPorIdentificacionClienteFault1Field;
            }
            set {
                this.consultarPorIdentificacionClienteFault1Field = value;
                this.RaisePropertyChanged("ConsultarPorIdentificacionClienteFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ClientesTouresBalon/")]
    public partial class ConsultarPorProductoClienteFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string consultarPorProductoClienteFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarPorProductoClienteFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ConsultarPorProductoClienteFault1 {
            get {
                return this.consultarPorProductoClienteFault1Field;
            }
            set {
                this.consultarPorProductoClienteFault1Field = value;
                this.RaisePropertyChanged("ConsultarPorProductoClienteFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.touresbalon.com/ClientesTouresBalon/")]
    public partial class ConsultarPorFactRangoClienteFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error consultarPorFactRangoClienteFault1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarPorFactRangoClienteFault", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Error ConsultarPorFactRangoClienteFault1 {
            get {
                return this.consultarPorFactRangoClienteFault1Field;
            }
            set {
                this.consultarPorFactRangoClienteFault1Field = value;
                this.RaisePropertyChanged("ConsultarPorFactRangoClienteFault1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", ConfigurationName="ServicioClientes.ClientesTouresBalon")]
    public interface ClientesTouresBalon {
        
        // CODEGEN: Parameter 'registrarClienteResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/RegistrarCliente", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioClientes.RegistrarClienteFault), Action="http://www.touresbalon.com/ClientesTouresBalon/RegistrarCliente", Name="RegistrarClienteFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="registrarClienteResponse")]
        B2CTouresBalon.ServicioClientes.RegistrarClienteResponse RegistrarCliente(B2CTouresBalon.ServicioClientes.RegistrarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/RegistrarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.RegistrarClienteResponse> RegistrarClienteAsync(B2CTouresBalon.ServicioClientes.RegistrarClienteRequest request);
        
        // CODEGEN: Parameter 'respuesta' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/AutenticarCliente", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioClientes.AutenticarClienteFault), Action="http://www.touresbalon.com/ClientesTouresBalon/AutenticarCliente", Name="AutenticarClienteFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="respuesta")]
        B2CTouresBalon.ServicioClientes.AutenticarClienteResponse AutenticarCliente(B2CTouresBalon.ServicioClientes.AutenticarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/AutenticarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.AutenticarClienteResponse> AutenticarClienteAsync(B2CTouresBalon.ServicioClientes.AutenticarClienteRequest request);
        
        // CODEGEN: Parameter 'respuesta' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/ActualizarCliente", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioClientes.ActualizarClienteFault), Action="http://www.touresbalon.com/ClientesTouresBalon/ActualizarCliente", Name="ActualizarClienteFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="respuesta")]
        B2CTouresBalon.ServicioClientes.ActualizarClienteResponse ActualizarCliente(B2CTouresBalon.ServicioClientes.ActualizarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/ActualizarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ActualizarClienteResponse> ActualizarClienteAsync(B2CTouresBalon.ServicioClientes.ActualizarClienteRequest request);
        
        // CODEGEN: Parameter 'respuesta' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/ActualizarContraseniaCliente", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioClientes.ActualizarContraseniaClienteFault), Action="http://www.touresbalon.com/ClientesTouresBalon/ActualizarContraseniaCliente", Name="ActualizarContraseniaClienteFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="respuesta")]
        B2CTouresBalon.ServicioClientes.ActualizarContraseniaClienteResponse ActualizarContraseniaCliente(B2CTouresBalon.ServicioClientes.ActualizarContraseniaClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/ActualizarContraseniaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ActualizarContraseniaClienteResponse> ActualizarContraseniaClienteAsync(B2CTouresBalon.ServicioClientes.ActualizarContraseniaClienteRequest request);
        
        // CODEGEN: Parameter 'respuesta' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/ActualizarEstatusCliente", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioClientes.ActualizarEstatusClienteFault), Action="http://www.touresbalon.com/ClientesTouresBalon/ActualizarEstatusCliente", Name="ActualizarEstatusClienteFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="respuesta")]
        B2CTouresBalon.ServicioClientes.ActualizarEstatusClienteResponse ActualizarEstatusCliente(B2CTouresBalon.ServicioClientes.ActualizarEstatusClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/ActualizarEstatusCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ActualizarEstatusClienteResponse> ActualizarEstatusClienteAsync(B2CTouresBalon.ServicioClientes.ActualizarEstatusClienteRequest request);
        
        // CODEGEN: Parameter 'cliente' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/ConsultarPorIdentificacionCliente", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioClientes.ConsultarPorIdentificacionClienteFault), Action="http://www.touresbalon.com/ClientesTouresBalon/ConsultarPorIdentificacionCliente", Name="ConsultarPorIdentificacionClienteFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cliente")]
        B2CTouresBalon.ServicioClientes.ConsultarPorIdentificacionClienteResponse ConsultarPorIdentificacionCliente(B2CTouresBalon.ServicioClientes.ConsultarPorIdentificacionClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/ConsultarPorIdentificacionCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ConsultarPorIdentificacionClienteResponse> ConsultarPorIdentificacionClienteAsync(B2CTouresBalon.ServicioClientes.ConsultarPorIdentificacionClienteRequest request);
        
        // CODEGEN: Parameter 'cliente' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/ConsultarPorProductoCliente", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioClientes.ConsultarPorProductoClienteFault), Action="http://www.touresbalon.com/ClientesTouresBalon/ConsultarPorProductoCliente", Name="ConsultarPorProductoClienteFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cliente")]
        B2CTouresBalon.ServicioClientes.ConsultarPorProductoClienteResponse ConsultarPorProductoCliente(B2CTouresBalon.ServicioClientes.ConsultarPorProductoClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/ConsultarPorProductoCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ConsultarPorProductoClienteResponse> ConsultarPorProductoClienteAsync(B2CTouresBalon.ServicioClientes.ConsultarPorProductoClienteRequest request);
        
        // CODEGEN: Parameter 'cliente' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/ConsultarPorFactRangoCliente", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(B2CTouresBalon.ServicioClientes.ConsultarPorFactRangoClienteFault), Action="http://www.touresbalon.com/ClientesTouresBalon/ConsultarPorFactRangoCliente", Name="ConsultarPorFactRangoClienteFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cliente")]
        B2CTouresBalon.ServicioClientes.ConsultarPorFactRangoClienteResponse ConsultarPorFactRangoCliente(B2CTouresBalon.ServicioClientes.ConsultarPorFactRangoClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.touresbalon.com/ClientesTouresBalon/ConsultarPorFactRangoCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ConsultarPorFactRangoClienteResponse> ConsultarPorFactRangoClienteAsync(B2CTouresBalon.ServicioClientes.ConsultarPorFactRangoClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarCliente", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class RegistrarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioClientes.Cliente cliente;
        
        public RegistrarClienteRequest() {
        }
        
        public RegistrarClienteRequest(B2CTouresBalon.ServicioClientes.Cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarClienteResponse", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class RegistrarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarClienteResponse", Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioClientes.RegistrarClienteReponseType registrarClienteResponse1;
        
        public RegistrarClienteResponse() {
        }
        
        public RegistrarClienteResponse(B2CTouresBalon.ServicioClientes.RegistrarClienteReponseType registrarClienteResponse1) {
            this.registrarClienteResponse1 = registrarClienteResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticarCliente", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class AutenticarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenia;
        
        public AutenticarClienteRequest() {
        }
        
        public AutenticarClienteRequest(string usuario, string contrasenia) {
            this.usuario = usuario;
            this.contrasenia = contrasenia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticarClienteResponse", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class AutenticarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioClientes.RespuestaGenerica respuesta;
        
        public AutenticarClienteResponse() {
        }
        
        public AutenticarClienteResponse(B2CTouresBalon.ServicioClientes.RespuestaGenerica respuesta) {
            this.respuesta = respuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarCliente", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class ActualizarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioClientes.Cliente cliente;
        
        public ActualizarClienteRequest() {
        }
        
        public ActualizarClienteRequest(B2CTouresBalon.ServicioClientes.Cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarClienteResponse", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class ActualizarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioClientes.RespuestaGenerica respuesta;
        
        public ActualizarClienteResponse() {
        }
        
        public ActualizarClienteResponse(B2CTouresBalon.ServicioClientes.RespuestaGenerica respuesta) {
            this.respuesta = respuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarContraseniaCliente", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class ActualizarContraseniaClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenia;
        
        public ActualizarContraseniaClienteRequest() {
        }
        
        public ActualizarContraseniaClienteRequest(string usuario, string contrasenia) {
            this.usuario = usuario;
            this.contrasenia = contrasenia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarContraseniaClienteResponse", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class ActualizarContraseniaClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioClientes.RespuestaGenerica respuesta;
        
        public ActualizarContraseniaClienteResponse() {
        }
        
        public ActualizarContraseniaClienteResponse(B2CTouresBalon.ServicioClientes.RespuestaGenerica respuesta) {
            this.respuesta = respuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarEstatusCliente", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class ActualizarEstatusClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioClientes.EstatusCliente estatus;
        
        public ActualizarEstatusClienteRequest() {
        }
        
        public ActualizarEstatusClienteRequest(int id_cliente, B2CTouresBalon.ServicioClientes.EstatusCliente estatus) {
            this.id_cliente = id_cliente;
            this.estatus = estatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarEstatusClienteResponse", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class ActualizarEstatusClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioClientes.RespuestaGenerica respuesta;
        
        public ActualizarEstatusClienteResponse() {
        }
        
        public ActualizarEstatusClienteResponse(B2CTouresBalon.ServicioClientes.RespuestaGenerica respuesta) {
            this.respuesta = respuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorIdentificacionCliente", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarPorIdentificacionClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_cliente;
        
        public ConsultarPorIdentificacionClienteRequest() {
        }
        
        public ConsultarPorIdentificacionClienteRequest(int id_cliente) {
            this.id_cliente = id_cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorIdentificacionClienteResponse", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarPorIdentificacionClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioClientes.Cliente cliente;
        
        public ConsultarPorIdentificacionClienteResponse() {
        }
        
        public ConsultarPorIdentificacionClienteResponse(B2CTouresBalon.ServicioClientes.Cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorProductoCliente", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarPorProductoClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_producto;
        
        public ConsultarPorProductoClienteRequest() {
        }
        
        public ConsultarPorProductoClienteRequest(int id_producto) {
            this.id_producto = id_producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorProductoClienteResponse", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarPorProductoClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("cliente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioClientes.Cliente[] cliente;
        
        public ConsultarPorProductoClienteResponse() {
        }
        
        public ConsultarPorProductoClienteResponse(B2CTouresBalon.ServicioClientes.Cliente[] cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorFactRangoCliente", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarPorFactRangoClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_inicial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_fin;
        
        public ConsultarPorFactRangoClienteRequest() {
        }
        
        public ConsultarPorFactRangoClienteRequest(System.DateTime fecha_inicial, System.DateTime fecha_fin) {
            this.fecha_inicial = fecha_inicial;
            this.fecha_fin = fecha_fin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarPorFactRangoClienteResponse", WrapperNamespace="http://www.touresbalon.com/ClientesTouresBalon/", IsWrapped=true)]
    public partial class ConsultarPorFactRangoClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.touresbalon.com/ClientesTouresBalon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("cliente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public B2CTouresBalon.ServicioClientes.Cliente[] cliente;
        
        public ConsultarPorFactRangoClienteResponse() {
        }
        
        public ConsultarPorFactRangoClienteResponse(B2CTouresBalon.ServicioClientes.Cliente[] cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientesTouresBalonChannel : B2CTouresBalon.ServicioClientes.ClientesTouresBalon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientesTouresBalonClient : System.ServiceModel.ClientBase<B2CTouresBalon.ServicioClientes.ClientesTouresBalon>, B2CTouresBalon.ServicioClientes.ClientesTouresBalon {
        
        public ClientesTouresBalonClient() {
        }
        
        public ClientesTouresBalonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientesTouresBalonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesTouresBalonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesTouresBalonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioClientes.RegistrarClienteResponse B2CTouresBalon.ServicioClientes.ClientesTouresBalon.RegistrarCliente(B2CTouresBalon.ServicioClientes.RegistrarClienteRequest request) {
            return base.Channel.RegistrarCliente(request);
        }
        
        public B2CTouresBalon.ServicioClientes.RegistrarClienteReponseType RegistrarCliente(B2CTouresBalon.ServicioClientes.Cliente cliente) {
            B2CTouresBalon.ServicioClientes.RegistrarClienteRequest inValue = new B2CTouresBalon.ServicioClientes.RegistrarClienteRequest();
            inValue.cliente = cliente;
            B2CTouresBalon.ServicioClientes.RegistrarClienteResponse retVal = ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).RegistrarCliente(inValue);
            return retVal.registrarClienteResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.RegistrarClienteResponse> B2CTouresBalon.ServicioClientes.ClientesTouresBalon.RegistrarClienteAsync(B2CTouresBalon.ServicioClientes.RegistrarClienteRequest request) {
            return base.Channel.RegistrarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.RegistrarClienteResponse> RegistrarClienteAsync(B2CTouresBalon.ServicioClientes.Cliente cliente) {
            B2CTouresBalon.ServicioClientes.RegistrarClienteRequest inValue = new B2CTouresBalon.ServicioClientes.RegistrarClienteRequest();
            inValue.cliente = cliente;
            return ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).RegistrarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioClientes.AutenticarClienteResponse B2CTouresBalon.ServicioClientes.ClientesTouresBalon.AutenticarCliente(B2CTouresBalon.ServicioClientes.AutenticarClienteRequest request) {
            return base.Channel.AutenticarCliente(request);
        }
        
        public B2CTouresBalon.ServicioClientes.RespuestaGenerica AutenticarCliente(string usuario, string contrasenia) {
            B2CTouresBalon.ServicioClientes.AutenticarClienteRequest inValue = new B2CTouresBalon.ServicioClientes.AutenticarClienteRequest();
            inValue.usuario = usuario;
            inValue.contrasenia = contrasenia;
            B2CTouresBalon.ServicioClientes.AutenticarClienteResponse retVal = ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).AutenticarCliente(inValue);
            return retVal.respuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.AutenticarClienteResponse> B2CTouresBalon.ServicioClientes.ClientesTouresBalon.AutenticarClienteAsync(B2CTouresBalon.ServicioClientes.AutenticarClienteRequest request) {
            return base.Channel.AutenticarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.AutenticarClienteResponse> AutenticarClienteAsync(string usuario, string contrasenia) {
            B2CTouresBalon.ServicioClientes.AutenticarClienteRequest inValue = new B2CTouresBalon.ServicioClientes.AutenticarClienteRequest();
            inValue.usuario = usuario;
            inValue.contrasenia = contrasenia;
            return ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).AutenticarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioClientes.ActualizarClienteResponse B2CTouresBalon.ServicioClientes.ClientesTouresBalon.ActualizarCliente(B2CTouresBalon.ServicioClientes.ActualizarClienteRequest request) {
            return base.Channel.ActualizarCliente(request);
        }
        
        public B2CTouresBalon.ServicioClientes.RespuestaGenerica ActualizarCliente(B2CTouresBalon.ServicioClientes.Cliente cliente) {
            B2CTouresBalon.ServicioClientes.ActualizarClienteRequest inValue = new B2CTouresBalon.ServicioClientes.ActualizarClienteRequest();
            inValue.cliente = cliente;
            B2CTouresBalon.ServicioClientes.ActualizarClienteResponse retVal = ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).ActualizarCliente(inValue);
            return retVal.respuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ActualizarClienteResponse> B2CTouresBalon.ServicioClientes.ClientesTouresBalon.ActualizarClienteAsync(B2CTouresBalon.ServicioClientes.ActualizarClienteRequest request) {
            return base.Channel.ActualizarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ActualizarClienteResponse> ActualizarClienteAsync(B2CTouresBalon.ServicioClientes.Cliente cliente) {
            B2CTouresBalon.ServicioClientes.ActualizarClienteRequest inValue = new B2CTouresBalon.ServicioClientes.ActualizarClienteRequest();
            inValue.cliente = cliente;
            return ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).ActualizarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioClientes.ActualizarContraseniaClienteResponse B2CTouresBalon.ServicioClientes.ClientesTouresBalon.ActualizarContraseniaCliente(B2CTouresBalon.ServicioClientes.ActualizarContraseniaClienteRequest request) {
            return base.Channel.ActualizarContraseniaCliente(request);
        }
        
        public B2CTouresBalon.ServicioClientes.RespuestaGenerica ActualizarContraseniaCliente(string usuario, string contrasenia) {
            B2CTouresBalon.ServicioClientes.ActualizarContraseniaClienteRequest inValue = new B2CTouresBalon.ServicioClientes.ActualizarContraseniaClienteRequest();
            inValue.usuario = usuario;
            inValue.contrasenia = contrasenia;
            B2CTouresBalon.ServicioClientes.ActualizarContraseniaClienteResponse retVal = ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).ActualizarContraseniaCliente(inValue);
            return retVal.respuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ActualizarContraseniaClienteResponse> B2CTouresBalon.ServicioClientes.ClientesTouresBalon.ActualizarContraseniaClienteAsync(B2CTouresBalon.ServicioClientes.ActualizarContraseniaClienteRequest request) {
            return base.Channel.ActualizarContraseniaClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ActualizarContraseniaClienteResponse> ActualizarContraseniaClienteAsync(string usuario, string contrasenia) {
            B2CTouresBalon.ServicioClientes.ActualizarContraseniaClienteRequest inValue = new B2CTouresBalon.ServicioClientes.ActualizarContraseniaClienteRequest();
            inValue.usuario = usuario;
            inValue.contrasenia = contrasenia;
            return ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).ActualizarContraseniaClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioClientes.ActualizarEstatusClienteResponse B2CTouresBalon.ServicioClientes.ClientesTouresBalon.ActualizarEstatusCliente(B2CTouresBalon.ServicioClientes.ActualizarEstatusClienteRequest request) {
            return base.Channel.ActualizarEstatusCliente(request);
        }
        
        public B2CTouresBalon.ServicioClientes.RespuestaGenerica ActualizarEstatusCliente(int id_cliente, B2CTouresBalon.ServicioClientes.EstatusCliente estatus) {
            B2CTouresBalon.ServicioClientes.ActualizarEstatusClienteRequest inValue = new B2CTouresBalon.ServicioClientes.ActualizarEstatusClienteRequest();
            inValue.id_cliente = id_cliente;
            inValue.estatus = estatus;
            B2CTouresBalon.ServicioClientes.ActualizarEstatusClienteResponse retVal = ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).ActualizarEstatusCliente(inValue);
            return retVal.respuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ActualizarEstatusClienteResponse> B2CTouresBalon.ServicioClientes.ClientesTouresBalon.ActualizarEstatusClienteAsync(B2CTouresBalon.ServicioClientes.ActualizarEstatusClienteRequest request) {
            return base.Channel.ActualizarEstatusClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ActualizarEstatusClienteResponse> ActualizarEstatusClienteAsync(int id_cliente, B2CTouresBalon.ServicioClientes.EstatusCliente estatus) {
            B2CTouresBalon.ServicioClientes.ActualizarEstatusClienteRequest inValue = new B2CTouresBalon.ServicioClientes.ActualizarEstatusClienteRequest();
            inValue.id_cliente = id_cliente;
            inValue.estatus = estatus;
            return ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).ActualizarEstatusClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioClientes.ConsultarPorIdentificacionClienteResponse B2CTouresBalon.ServicioClientes.ClientesTouresBalon.ConsultarPorIdentificacionCliente(B2CTouresBalon.ServicioClientes.ConsultarPorIdentificacionClienteRequest request) {
            return base.Channel.ConsultarPorIdentificacionCliente(request);
        }
        
        public B2CTouresBalon.ServicioClientes.Cliente ConsultarPorIdentificacionCliente(int id_cliente) {
            B2CTouresBalon.ServicioClientes.ConsultarPorIdentificacionClienteRequest inValue = new B2CTouresBalon.ServicioClientes.ConsultarPorIdentificacionClienteRequest();
            inValue.id_cliente = id_cliente;
            B2CTouresBalon.ServicioClientes.ConsultarPorIdentificacionClienteResponse retVal = ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).ConsultarPorIdentificacionCliente(inValue);
            return retVal.cliente;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ConsultarPorIdentificacionClienteResponse> B2CTouresBalon.ServicioClientes.ClientesTouresBalon.ConsultarPorIdentificacionClienteAsync(B2CTouresBalon.ServicioClientes.ConsultarPorIdentificacionClienteRequest request) {
            return base.Channel.ConsultarPorIdentificacionClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ConsultarPorIdentificacionClienteResponse> ConsultarPorIdentificacionClienteAsync(int id_cliente) {
            B2CTouresBalon.ServicioClientes.ConsultarPorIdentificacionClienteRequest inValue = new B2CTouresBalon.ServicioClientes.ConsultarPorIdentificacionClienteRequest();
            inValue.id_cliente = id_cliente;
            return ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).ConsultarPorIdentificacionClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioClientes.ConsultarPorProductoClienteResponse B2CTouresBalon.ServicioClientes.ClientesTouresBalon.ConsultarPorProductoCliente(B2CTouresBalon.ServicioClientes.ConsultarPorProductoClienteRequest request) {
            return base.Channel.ConsultarPorProductoCliente(request);
        }
        
        public B2CTouresBalon.ServicioClientes.Cliente[] ConsultarPorProductoCliente(int id_producto) {
            B2CTouresBalon.ServicioClientes.ConsultarPorProductoClienteRequest inValue = new B2CTouresBalon.ServicioClientes.ConsultarPorProductoClienteRequest();
            inValue.id_producto = id_producto;
            B2CTouresBalon.ServicioClientes.ConsultarPorProductoClienteResponse retVal = ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).ConsultarPorProductoCliente(inValue);
            return retVal.cliente;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ConsultarPorProductoClienteResponse> B2CTouresBalon.ServicioClientes.ClientesTouresBalon.ConsultarPorProductoClienteAsync(B2CTouresBalon.ServicioClientes.ConsultarPorProductoClienteRequest request) {
            return base.Channel.ConsultarPorProductoClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ConsultarPorProductoClienteResponse> ConsultarPorProductoClienteAsync(int id_producto) {
            B2CTouresBalon.ServicioClientes.ConsultarPorProductoClienteRequest inValue = new B2CTouresBalon.ServicioClientes.ConsultarPorProductoClienteRequest();
            inValue.id_producto = id_producto;
            return ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).ConsultarPorProductoClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2CTouresBalon.ServicioClientes.ConsultarPorFactRangoClienteResponse B2CTouresBalon.ServicioClientes.ClientesTouresBalon.ConsultarPorFactRangoCliente(B2CTouresBalon.ServicioClientes.ConsultarPorFactRangoClienteRequest request) {
            return base.Channel.ConsultarPorFactRangoCliente(request);
        }
        
        public B2CTouresBalon.ServicioClientes.Cliente[] ConsultarPorFactRangoCliente(System.DateTime fecha_inicial, System.DateTime fecha_fin) {
            B2CTouresBalon.ServicioClientes.ConsultarPorFactRangoClienteRequest inValue = new B2CTouresBalon.ServicioClientes.ConsultarPorFactRangoClienteRequest();
            inValue.fecha_inicial = fecha_inicial;
            inValue.fecha_fin = fecha_fin;
            B2CTouresBalon.ServicioClientes.ConsultarPorFactRangoClienteResponse retVal = ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).ConsultarPorFactRangoCliente(inValue);
            return retVal.cliente;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ConsultarPorFactRangoClienteResponse> B2CTouresBalon.ServicioClientes.ClientesTouresBalon.ConsultarPorFactRangoClienteAsync(B2CTouresBalon.ServicioClientes.ConsultarPorFactRangoClienteRequest request) {
            return base.Channel.ConsultarPorFactRangoClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<B2CTouresBalon.ServicioClientes.ConsultarPorFactRangoClienteResponse> ConsultarPorFactRangoClienteAsync(System.DateTime fecha_inicial, System.DateTime fecha_fin) {
            B2CTouresBalon.ServicioClientes.ConsultarPorFactRangoClienteRequest inValue = new B2CTouresBalon.ServicioClientes.ConsultarPorFactRangoClienteRequest();
            inValue.fecha_inicial = fecha_inicial;
            inValue.fecha_fin = fecha_fin;
            return ((B2CTouresBalon.ServicioClientes.ClientesTouresBalon)(this)).ConsultarPorFactRangoClienteAsync(inValue);
        }
    }
}
